//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ir.Shaparak.Sadad
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckStatusResult", Namespace="http://tempuri.org/")]
    public partial class CheckStatusResult : object
    {
        
        private string RefrenceNumberField;
        
        private string BankReciptNumberField;
        
        private bool NewlyCommittedField;
        
        private int FailCodeField;
        
        private string ResponseCodeField;
        
        private long TraceNoField;
        
        private string ShamsiDateField;
        
        private System.DateTime RealTransactionDateTimeField;
        
        private int AppStatusField;
        
        private string AppStatusDescriptionField;
        
        private int AppStatusCodeField;
        
        private string CustomerCardNumberField;
        
        private string CardHolderAccNumberField;
        
        private string CardHolderNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RefrenceNumber
        {
            get
            {
                return this.RefrenceNumberField;
            }
            set
            {
                this.RefrenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BankReciptNumber
        {
            get
            {
                return this.BankReciptNumberField;
            }
            set
            {
                this.BankReciptNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool NewlyCommitted
        {
            get
            {
                return this.NewlyCommittedField;
            }
            set
            {
                this.NewlyCommittedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int FailCode
        {
            get
            {
                return this.FailCodeField;
            }
            set
            {
                this.FailCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long TraceNo
        {
            get
            {
                return this.TraceNoField;
            }
            set
            {
                this.TraceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ShamsiDate
        {
            get
            {
                return this.ShamsiDateField;
            }
            set
            {
                this.ShamsiDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime RealTransactionDateTime
        {
            get
            {
                return this.RealTransactionDateTimeField;
            }
            set
            {
                this.RealTransactionDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int AppStatus
        {
            get
            {
                return this.AppStatusField;
            }
            set
            {
                this.AppStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string AppStatusDescription
        {
            get
            {
                return this.AppStatusDescriptionField;
            }
            set
            {
                this.AppStatusDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int AppStatusCode
        {
            get
            {
                return this.AppStatusCodeField;
            }
            set
            {
                this.AppStatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string CustomerCardNumber
        {
            get
            {
                return this.CustomerCardNumberField;
            }
            set
            {
                this.CustomerCardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string CardHolderAccNumber
        {
            get
            {
                return this.CardHolderAccNumberField;
            }
            set
            {
                this.CardHolderAccNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CardHolderName
        {
            get
            {
                return this.CardHolderNameField;
            }
            set
            {
                this.CardHolderNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://tempuri.org/")]
    public partial class Transaction : object
    {
        
        private long MessageTypeIdField;
        
        private string CardNumberField;
        
        private string ProcessingCodeField;
        
        private long AmountTransField;
        
        private string DateTimeSendShetabField;
        
        private int TraceNoField;
        
        private long TimeLocalTransField;
        
        private long DateLocalTransField;
        
        private string TypeOfPinInputField;
        
        private string TerminalTypeField;
        
        private long MerchantBankIdField;
        
        private long IssueBankIdField;
        
        private long RetrivalRefNoField;
        
        private string RefrenceNumberField;
        
        private string ResponseField;
        
        private int ResponseCodeField;
        
        private long TerminalIdField;
        
        private long CardAcqIdField;
        
        private string CardAcqNameField;
        
        private string CurrencyCodeField;
        
        private string MerchantUrlField;
        
        private string MerchantIPField;
        
        private long OrderIdField;
        
        private string AppStatusField;
        
        private string FailCodeField;
        
        private string StateListField;
        
        private string UpdateTimeField;
        
        private string CreateDateTimeField;
        
        private string RequestKeyField;
        
        private string ShamsiDateField;
        
        private string tblNameField;
        
        private string DestinationCardHolderNameField;
        
        private string CardHolderEmailAddressField;
        
        private string DestinationAccountNumberField;
        
        private string AdditionalData_Transaction_P48Field;
        
        private string SecondAccNumberField;
        
        private string AdditionalData_TransactionLicenseField;
        
        private System.Nullable<int> LineField;
        
        private long BillIDField;
        
        private long BillPaymentIDField;
        
        private string CardHolderIPField;
        
        private string MerchantAdditionalDataField;
        
        private string DestinationPrimaryAccNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MessageTypeId
        {
            get
            {
                return this.MessageTypeIdField;
            }
            set
            {
                this.MessageTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProcessingCode
        {
            get
            {
                return this.ProcessingCodeField;
            }
            set
            {
                this.ProcessingCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long AmountTrans
        {
            get
            {
                return this.AmountTransField;
            }
            set
            {
                this.AmountTransField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DateTimeSendShetab
        {
            get
            {
                return this.DateTimeSendShetabField;
            }
            set
            {
                this.DateTimeSendShetabField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int TraceNo
        {
            get
            {
                return this.TraceNoField;
            }
            set
            {
                this.TraceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public long TimeLocalTrans
        {
            get
            {
                return this.TimeLocalTransField;
            }
            set
            {
                this.TimeLocalTransField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public long DateLocalTrans
        {
            get
            {
                return this.DateLocalTransField;
            }
            set
            {
                this.DateLocalTransField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TypeOfPinInput
        {
            get
            {
                return this.TypeOfPinInputField;
            }
            set
            {
                this.TypeOfPinInputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TerminalType
        {
            get
            {
                return this.TerminalTypeField;
            }
            set
            {
                this.TerminalTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public long MerchantBankId
        {
            get
            {
                return this.MerchantBankIdField;
            }
            set
            {
                this.MerchantBankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public long IssueBankId
        {
            get
            {
                return this.IssueBankIdField;
            }
            set
            {
                this.IssueBankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public long RetrivalRefNo
        {
            get
            {
                return this.RetrivalRefNoField;
            }
            set
            {
                this.RetrivalRefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string RefrenceNumber
        {
            get
            {
                return this.RefrenceNumberField;
            }
            set
            {
                this.RefrenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Response
        {
            get
            {
                return this.ResponseField;
            }
            set
            {
                this.ResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public long TerminalId
        {
            get
            {
                return this.TerminalIdField;
            }
            set
            {
                this.TerminalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public long CardAcqId
        {
            get
            {
                return this.CardAcqIdField;
            }
            set
            {
                this.CardAcqIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string CardAcqName
        {
            get
            {
                return this.CardAcqNameField;
            }
            set
            {
                this.CardAcqNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string MerchantUrl
        {
            get
            {
                return this.MerchantUrlField;
            }
            set
            {
                this.MerchantUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string MerchantIP
        {
            get
            {
                return this.MerchantIPField;
            }
            set
            {
                this.MerchantIPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public long OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string AppStatus
        {
            get
            {
                return this.AppStatusField;
            }
            set
            {
                this.AppStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string FailCode
        {
            get
            {
                return this.FailCodeField;
            }
            set
            {
                this.FailCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string StateList
        {
            get
            {
                return this.StateListField;
            }
            set
            {
                this.StateListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string UpdateTime
        {
            get
            {
                return this.UpdateTimeField;
            }
            set
            {
                this.UpdateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string CreateDateTime
        {
            get
            {
                return this.CreateDateTimeField;
            }
            set
            {
                this.CreateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string RequestKey
        {
            get
            {
                return this.RequestKeyField;
            }
            set
            {
                this.RequestKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string ShamsiDate
        {
            get
            {
                return this.ShamsiDateField;
            }
            set
            {
                this.ShamsiDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string tblName
        {
            get
            {
                return this.tblNameField;
            }
            set
            {
                this.tblNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string DestinationCardHolderName
        {
            get
            {
                return this.DestinationCardHolderNameField;
            }
            set
            {
                this.DestinationCardHolderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string CardHolderEmailAddress
        {
            get
            {
                return this.CardHolderEmailAddressField;
            }
            set
            {
                this.CardHolderEmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string DestinationAccountNumber
        {
            get
            {
                return this.DestinationAccountNumberField;
            }
            set
            {
                this.DestinationAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string AdditionalData_Transaction_P48
        {
            get
            {
                return this.AdditionalData_Transaction_P48Field;
            }
            set
            {
                this.AdditionalData_Transaction_P48Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string SecondAccNumber
        {
            get
            {
                return this.SecondAccNumberField;
            }
            set
            {
                this.SecondAccNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string AdditionalData_TransactionLicense
        {
            get
            {
                return this.AdditionalData_TransactionLicenseField;
            }
            set
            {
                this.AdditionalData_TransactionLicenseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=37)]
        public System.Nullable<int> Line
        {
            get
            {
                return this.LineField;
            }
            set
            {
                this.LineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=38)]
        public long BillID
        {
            get
            {
                return this.BillIDField;
            }
            set
            {
                this.BillIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=39)]
        public long BillPaymentID
        {
            get
            {
                return this.BillPaymentIDField;
            }
            set
            {
                this.BillPaymentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string CardHolderIP
        {
            get
            {
                return this.CardHolderIPField;
            }
            set
            {
                this.CardHolderIPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string MerchantAdditionalData
        {
            get
            {
                return this.MerchantAdditionalDataField;
            }
            set
            {
                this.MerchantAdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string DestinationPrimaryAccNum
        {
            get
            {
                return this.DestinationPrimaryAccNumField;
            }
            set
            {
                this.DestinationPrimaryAccNumField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Ir.Shaparak.Sadad.MerchantUtilitySoap")]
    public interface MerchantUtilitySoap
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckRequestStatusWithRealTransactionDateTime", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckRequestStatusWithRealTransactionDateTimeResponse> CheckRequestStatusWithRealTransactionDateTimeAsync(Ir.Shaparak.Sadad.CheckRequestStatusWithRealTransactionDateTimeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckRequestStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckRequestStatusResponse> CheckRequestStatusAsync(Ir.Shaparak.Sadad.CheckRequestStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckRequestStatusEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckRequestStatusExResponse> CheckRequestStatusExAsync(Ir.Shaparak.Sadad.CheckRequestStatusExRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckRequestStatusExWithRealTransactionDateTime", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckRequestStatusExWithRealTransactionDateTimeResponse> CheckRequestStatusExWithRealTransactionDateTimeAsync(Ir.Shaparak.Sadad.CheckRequestStatusExWithRealTransactionDateTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckRequestStatusWithResult", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckStatusResult> CheckRequestStatusResultAsync(long OrderID, string CardAcqID, string TerminalID, string TransactionKey, string RequestKey, long AmountTrans);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRequestStatusResult", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckStatusResult> GetRequestStatusResultAsync(long OrderID, string CardAcqID, string TerminalID, string TransactionKey, string RequestKey, long AmountTrans);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAuthRequestStatus", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckStatusResult> GetAuthRequestStatusAsync(string CardAcqID, string TerminalID, long OrderID, string RequestKey, string CardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckBatchTransferStatus", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckStatusResult> CheckBatchTransferStatusAsync(string CardAcqID, string TerminalID, long OrderID, string RequestKey, string CardNum, long Amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckBillStatus", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckStatusResult> CheckBillStatusAsync(string CardAcqID, string TerminalID, long OrderID, string RequestKey, long BillID, long BillPaymentID);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpecificMerchantCommitReportByPageNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.GetSpecificMerchantCommitReportByPageNumberResponse> GetSpecificMerchantCommitReportByPageNumberAsync(Ir.Shaparak.Sadad.GetSpecificMerchantCommitReportByPageNumberRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommitReportByPageNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.GetCommitReportByPageNumberResponse> GetCommitReportByPageNumberAsync(Ir.Shaparak.Sadad.GetCommitReportByPageNumberRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommitReport", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.GetCommitReportResponse> GetCommitReportAsync(Ir.Shaparak.Sadad.GetCommitReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTransactionReport", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.GetTransactionReportResponse> GetTransactionReportAsync(Ir.Shaparak.Sadad.GetTransactionReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTransactionReportByPageNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.GetTransactionReportByPageNumberResponse> GetTransactionReportByPageNumberAsync(Ir.Shaparak.Sadad.GetTransactionReportByPageNumberRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTransactionReportWithSatlementDateByPageNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.GetTransactionReportWithSettlementDateByPageNumberResponse> GetTransactionReportWithSettlementDateByPageNumberAsync(Ir.Shaparak.Sadad.GetTransactionReportWithSettlementDateByPageNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneratePaymentID", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        System.Threading.Tasks.Task<string> GeneratePaymentIDAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidatePaymentID", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        System.Threading.Tasks.Task<bool> ValidatePaymentIDAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateCheckDigit", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        System.Threading.Tasks.Task<string> GenerateCheckDigitAsync(string ID);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaymentUtility", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.PaymentUtilityResponse> PaymentUtilityAsync(Ir.Shaparak.Sadad.PaymentUtilityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaymentUtilityAdditionalData", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.PaymentUtilityAdditionalDataResponse> PaymentUtilityAdditionalDataAsync(Ir.Shaparak.Sadad.PaymentUtilityAdditionalDataRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaymentUtilityOptionalParameter", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.PaymentUtilityOptionalParameterResponse> PaymentUtilityOptionalParameterAsync(Ir.Shaparak.Sadad.PaymentUtilityOptionalParameterRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BillPaymentUtility", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.BillPaymentUtilityResponse> BillPaymentUtilityAsync(Ir.Shaparak.Sadad.BillPaymentUtilityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchTransferUtility", ReplyAction="*")]
        System.Threading.Tasks.Task<Ir.Shaparak.Sadad.BatchTransferUtilityResponse> BatchTransferUtilityAsync(Ir.Shaparak.Sadad.BatchTransferUtilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcTimeStamp", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        System.Threading.Tasks.Task<string> CalcTimeStampAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRequestStatusWithRealTransactionDateTime", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckRequestStatusWithRealTransactionDateTimeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long OrderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string CardAcqID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string TerminalID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string TransactionKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string RequestKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public long AmountTrans;
        
        public CheckRequestStatusWithRealTransactionDateTimeRequest()
        {
        }
        
        public CheckRequestStatusWithRealTransactionDateTimeRequest(long OrderID, string CardAcqID, string TerminalID, string TransactionKey, string RequestKey, long AmountTrans)
        {
            this.OrderID = OrderID;
            this.CardAcqID = CardAcqID;
            this.TerminalID = TerminalID;
            this.TransactionKey = TransactionKey;
            this.RequestKey = RequestKey;
            this.AmountTrans = AmountTrans;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRequestStatusWithRealTransactionDateTimeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckRequestStatusWithRealTransactionDateTimeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int CheckRequestStatusWithRealTransactionDateTimeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RetrivalRefNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string AppStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string RealTransactionDateTime;
        
        public CheckRequestStatusWithRealTransactionDateTimeResponse()
        {
        }
        
        public CheckRequestStatusWithRealTransactionDateTimeResponse(int CheckRequestStatusWithRealTransactionDateTimeResult, string RetrivalRefNo, string AppStatus, string RealTransactionDateTime)
        {
            this.CheckRequestStatusWithRealTransactionDateTimeResult = CheckRequestStatusWithRealTransactionDateTimeResult;
            this.RetrivalRefNo = RetrivalRefNo;
            this.AppStatus = AppStatus;
            this.RealTransactionDateTime = RealTransactionDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRequestStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckRequestStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long OrderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string CardAcqID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string TerminalID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string transactionKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string RequestKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public long AmountTrans;
        
        public CheckRequestStatusRequest()
        {
        }
        
        public CheckRequestStatusRequest(long OrderID, string CardAcqID, string TerminalID, string transactionKey, string RequestKey, long AmountTrans)
        {
            this.OrderID = OrderID;
            this.CardAcqID = CardAcqID;
            this.TerminalID = TerminalID;
            this.transactionKey = transactionKey;
            this.RequestKey = RequestKey;
            this.AmountTrans = AmountTrans;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRequestStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckRequestStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int CheckRequestStatusResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RetrivalRefNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string AppStatus;
        
        public CheckRequestStatusResponse()
        {
        }
        
        public CheckRequestStatusResponse(int CheckRequestStatusResult, string RetrivalRefNo, string AppStatus)
        {
            this.CheckRequestStatusResult = CheckRequestStatusResult;
            this.RetrivalRefNo = RetrivalRefNo;
            this.AppStatus = AppStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRequestStatusEx", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckRequestStatusExRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long OrderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public long AmountTrans;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string CardAcqID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string TerminalID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string RequestKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string TimeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string FP;
        
        public CheckRequestStatusExRequest()
        {
        }
        
        public CheckRequestStatusExRequest(long OrderID, long AmountTrans, string CardAcqID, string TerminalID, string RequestKey, string TimeStamp, string FP)
        {
            this.OrderID = OrderID;
            this.AmountTrans = AmountTrans;
            this.CardAcqID = CardAcqID;
            this.TerminalID = TerminalID;
            this.RequestKey = RequestKey;
            this.TimeStamp = TimeStamp;
            this.FP = FP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRequestStatusExResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckRequestStatusExResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int CheckRequestStatusExResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RetrievalRefNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string AppStatus;
        
        public CheckRequestStatusExResponse()
        {
        }
        
        public CheckRequestStatusExResponse(int CheckRequestStatusExResult, string RetrievalRefNo, string AppStatus)
        {
            this.CheckRequestStatusExResult = CheckRequestStatusExResult;
            this.RetrievalRefNo = RetrievalRefNo;
            this.AppStatus = AppStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRequestStatusExWithRealTransactionDateTime", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckRequestStatusExWithRealTransactionDateTimeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long OrderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public long AmountTrans;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string CardAcqID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string TerminalID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string RequestKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string TimeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string FP;
        
        public CheckRequestStatusExWithRealTransactionDateTimeRequest()
        {
        }
        
        public CheckRequestStatusExWithRealTransactionDateTimeRequest(long OrderID, long AmountTrans, string CardAcqID, string TerminalID, string RequestKey, string TimeStamp, string FP)
        {
            this.OrderID = OrderID;
            this.AmountTrans = AmountTrans;
            this.CardAcqID = CardAcqID;
            this.TerminalID = TerminalID;
            this.RequestKey = RequestKey;
            this.TimeStamp = TimeStamp;
            this.FP = FP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRequestStatusExWithRealTransactionDateTimeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckRequestStatusExWithRealTransactionDateTimeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int CheckRequestStatusExWithRealTransactionDateTimeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RetrievalRefNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string AppStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string RealTransactionDateTime;
        
        public CheckRequestStatusExWithRealTransactionDateTimeResponse()
        {
        }
        
        public CheckRequestStatusExWithRealTransactionDateTimeResponse(int CheckRequestStatusExWithRealTransactionDateTimeResult, string RetrievalRefNo, string AppStatus, string RealTransactionDateTime)
        {
            this.CheckRequestStatusExWithRealTransactionDateTimeResult = CheckRequestStatusExWithRealTransactionDateTimeResult;
            this.RetrievalRefNo = RetrievalRefNo;
            this.AppStatus = AppStatus;
            this.RealTransactionDateTime = RealTransactionDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSpecificMerchantCommitReportByPageNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSpecificMerchantCommitReportByPageNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long Caller_MerchantId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public long Caller_TerminalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Caller_TimeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Caller_FP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public long MerchantId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public long TerminalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string FromShamsiDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string ToShamsiDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string FromHour;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string ToHour;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string TraceNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string Amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string OrderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public int PageNumber;
        
        public GetSpecificMerchantCommitReportByPageNumberRequest()
        {
        }
        
        public GetSpecificMerchantCommitReportByPageNumberRequest(long Caller_MerchantId, long Caller_TerminalId, string Caller_TimeStamp, string Caller_FP, long MerchantId, long TerminalId, string FromShamsiDate, string ToShamsiDate, string FromHour, string ToHour, string TraceNo, string Amount, string OrderId, int PageNumber)
        {
            this.Caller_MerchantId = Caller_MerchantId;
            this.Caller_TerminalId = Caller_TerminalId;
            this.Caller_TimeStamp = Caller_TimeStamp;
            this.Caller_FP = Caller_FP;
            this.MerchantId = MerchantId;
            this.TerminalId = TerminalId;
            this.FromShamsiDate = FromShamsiDate;
            this.ToShamsiDate = ToShamsiDate;
            this.FromHour = FromHour;
            this.ToHour = ToHour;
            this.TraceNo = TraceNo;
            this.Amount = Amount;
            this.OrderId = OrderId;
            this.PageNumber = PageNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSpecificMerchantCommitReportByPageNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSpecificMerchantCommitReportByPageNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Ir.Shaparak.Sadad.Transaction[] GetSpecificMerchantCommitReportByPageNumberResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int TotalPage;
        
        public GetSpecificMerchantCommitReportByPageNumberResponse()
        {
        }
        
        public GetSpecificMerchantCommitReportByPageNumberResponse(Ir.Shaparak.Sadad.Transaction[] GetSpecificMerchantCommitReportByPageNumberResult, int TotalPage)
        {
            this.GetSpecificMerchantCommitReportByPageNumberResult = GetSpecificMerchantCommitReportByPageNumberResult;
            this.TotalPage = TotalPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCommitReportByPageNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCommitReportByPageNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string MerchantId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Terminal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string TimeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string FP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string FromShamsiDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string ToShamsiDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string FromHour;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string ToHour;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string TraceNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string Amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string OrderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public int PageNumber;
        
        public GetCommitReportByPageNumberRequest()
        {
        }
        
        public GetCommitReportByPageNumberRequest(string MerchantId, string Terminal, string TimeStamp, string FP, string FromShamsiDate, string ToShamsiDate, string FromHour, string ToHour, string TraceNo, string Amount, string OrderId, int PageNumber)
        {
            this.MerchantId = MerchantId;
            this.Terminal = Terminal;
            this.TimeStamp = TimeStamp;
            this.FP = FP;
            this.FromShamsiDate = FromShamsiDate;
            this.ToShamsiDate = ToShamsiDate;
            this.FromHour = FromHour;
            this.ToHour = ToHour;
            this.TraceNo = TraceNo;
            this.Amount = Amount;
            this.OrderId = OrderId;
            this.PageNumber = PageNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCommitReportByPageNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCommitReportByPageNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string GetCommitReportByPageNumberResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int TotalPage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XMLReportSchema;
        
        public GetCommitReportByPageNumberResponse()
        {
        }
        
        public GetCommitReportByPageNumberResponse(string GetCommitReportByPageNumberResult, int TotalPage, string XMLReportSchema)
        {
            this.GetCommitReportByPageNumberResult = GetCommitReportByPageNumberResult;
            this.TotalPage = TotalPage;
            this.XMLReportSchema = XMLReportSchema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCommitReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCommitReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string MerchantId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Terminal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string TimeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string FP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string FromShamsiDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string ToShamsiDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string FromHour;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string ToHour;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string TraceNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string Amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string OrderId;
        
        public GetCommitReportRequest()
        {
        }
        
        public GetCommitReportRequest(string MerchantId, string Terminal, string TimeStamp, string FP, string FromShamsiDate, string ToShamsiDate, string FromHour, string ToHour, string TraceNo, string Amount, string OrderId)
        {
            this.MerchantId = MerchantId;
            this.Terminal = Terminal;
            this.TimeStamp = TimeStamp;
            this.FP = FP;
            this.FromShamsiDate = FromShamsiDate;
            this.ToShamsiDate = ToShamsiDate;
            this.FromHour = FromHour;
            this.ToHour = ToHour;
            this.TraceNo = TraceNo;
            this.Amount = Amount;
            this.OrderId = OrderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCommitReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCommitReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string GetCommitReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string XMLReportSchema;
        
        public GetCommitReportResponse()
        {
        }
        
        public GetCommitReportResponse(string GetCommitReportResult, string XMLReportSchema)
        {
            this.GetCommitReportResult = GetCommitReportResult;
            this.XMLReportSchema = XMLReportSchema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransactionReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTransactionReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string MerchantId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Terminal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string TimeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string FP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string ShamsiDate;
        
        public GetTransactionReportRequest()
        {
        }
        
        public GetTransactionReportRequest(string MerchantId, string Terminal, string TimeStamp, string FP, string ShamsiDate)
        {
            this.MerchantId = MerchantId;
            this.Terminal = Terminal;
            this.TimeStamp = TimeStamp;
            this.FP = FP;
            this.ShamsiDate = ShamsiDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransactionReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTransactionReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string GetTransactionReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string XMLReportSchema;
        
        public GetTransactionReportResponse()
        {
        }
        
        public GetTransactionReportResponse(string GetTransactionReportResult, string XMLReportSchema)
        {
            this.GetTransactionReportResult = GetTransactionReportResult;
            this.XMLReportSchema = XMLReportSchema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransactionReportByPageNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTransactionReportByPageNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string MerchantId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Terminal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string TimeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string FP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string ShamsiDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int PageNumber;
        
        public GetTransactionReportByPageNumberRequest()
        {
        }
        
        public GetTransactionReportByPageNumberRequest(string MerchantId, string Terminal, string TimeStamp, string FP, string ShamsiDate, int PageNumber)
        {
            this.MerchantId = MerchantId;
            this.Terminal = Terminal;
            this.TimeStamp = TimeStamp;
            this.FP = FP;
            this.ShamsiDate = ShamsiDate;
            this.PageNumber = PageNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransactionReportByPageNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTransactionReportByPageNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string GetTransactionReportByPageNumberResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int TotalPage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XMLReportSchema;
        
        public GetTransactionReportByPageNumberResponse()
        {
        }
        
        public GetTransactionReportByPageNumberResponse(string GetTransactionReportByPageNumberResult, int TotalPage, string XMLReportSchema)
        {
            this.GetTransactionReportByPageNumberResult = GetTransactionReportByPageNumberResult;
            this.TotalPage = TotalPage;
            this.XMLReportSchema = XMLReportSchema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransactionReportWithSettlementDateByPageNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTransactionReportWithSettlementDateByPageNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string MerchantId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Terminal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string TimeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string FP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string ShamsiDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string SettlementDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int PageNumber;
        
        public GetTransactionReportWithSettlementDateByPageNumberRequest()
        {
        }
        
        public GetTransactionReportWithSettlementDateByPageNumberRequest(string MerchantId, string Terminal, string TimeStamp, string FP, string ShamsiDate, string SettlementDate, int PageNumber)
        {
            this.MerchantId = MerchantId;
            this.Terminal = Terminal;
            this.TimeStamp = TimeStamp;
            this.FP = FP;
            this.ShamsiDate = ShamsiDate;
            this.SettlementDate = SettlementDate;
            this.PageNumber = PageNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransactionReportWithSettlementDateByPageNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTransactionReportWithSettlementDateByPageNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string GetTransactionReportWithSettlementDateByPageNumberResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int TotalPage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XMLReportSchema;
        
        public GetTransactionReportWithSettlementDateByPageNumberResponse()
        {
        }
        
        public GetTransactionReportWithSettlementDateByPageNumberResponse(string GetTransactionReportWithSettlementDateByPageNumberResult, int TotalPage, string XMLReportSchema)
        {
            this.GetTransactionReportWithSettlementDateByPageNumberResult = GetTransactionReportWithSettlementDateByPageNumberResult;
            this.TotalPage = TotalPage;
            this.XMLReportSchema = XMLReportSchema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaymentUtility", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaymentUtilityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string CardAcqID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public long AmountTrans;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public long OrderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string transactionKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string TerminalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string RedirectURL;
        
        public PaymentUtilityRequest()
        {
        }
        
        public PaymentUtilityRequest(string CardAcqID, long AmountTrans, long OrderId, string transactionKey, string TerminalId, string RedirectURL)
        {
            this.CardAcqID = CardAcqID;
            this.AmountTrans = AmountTrans;
            this.OrderId = OrderId;
            this.transactionKey = transactionKey;
            this.TerminalId = TerminalId;
            this.RedirectURL = RedirectURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaymentUtilityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaymentUtilityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string PaymentUtilityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RequestKey;
        
        public PaymentUtilityResponse()
        {
        }
        
        public PaymentUtilityResponse(string PaymentUtilityResult, string RequestKey)
        {
            this.PaymentUtilityResult = PaymentUtilityResult;
            this.RequestKey = RequestKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaymentUtilityAdditionalData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaymentUtilityAdditionalDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string CardAcqID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public long AmountTrans;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public long OrderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string transactionKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string TerminalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string RedirectURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string MerchantAdditionalData;
        
        public PaymentUtilityAdditionalDataRequest()
        {
        }
        
        public PaymentUtilityAdditionalDataRequest(string CardAcqID, long AmountTrans, long OrderId, string transactionKey, string TerminalId, string RedirectURL, string MerchantAdditionalData)
        {
            this.CardAcqID = CardAcqID;
            this.AmountTrans = AmountTrans;
            this.OrderId = OrderId;
            this.transactionKey = transactionKey;
            this.TerminalId = TerminalId;
            this.RedirectURL = RedirectURL;
            this.MerchantAdditionalData = MerchantAdditionalData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaymentUtilityAdditionalDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaymentUtilityAdditionalDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string PaymentUtilityAdditionalDataResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RequestKey;
        
        public PaymentUtilityAdditionalDataResponse()
        {
        }
        
        public PaymentUtilityAdditionalDataResponse(string PaymentUtilityAdditionalDataResult, string RequestKey)
        {
            this.PaymentUtilityAdditionalDataResult = PaymentUtilityAdditionalDataResult;
            this.RequestKey = RequestKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaymentUtilityOptionalParameter", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaymentUtilityOptionalParameterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string CardAcqID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public long AmountTrans;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public long OrderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string transactionKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string TerminalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string RedirectURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string MerchantAdditionalData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string CustomerEmailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string OptionalPaymentParameter;
        
        public PaymentUtilityOptionalParameterRequest()
        {
        }
        
        public PaymentUtilityOptionalParameterRequest(string CardAcqID, long AmountTrans, long OrderId, string transactionKey, string TerminalId, string RedirectURL, string MerchantAdditionalData, string CustomerEmailAddress, string OptionalPaymentParameter)
        {
            this.CardAcqID = CardAcqID;
            this.AmountTrans = AmountTrans;
            this.OrderId = OrderId;
            this.transactionKey = transactionKey;
            this.TerminalId = TerminalId;
            this.RedirectURL = RedirectURL;
            this.MerchantAdditionalData = MerchantAdditionalData;
            this.CustomerEmailAddress = CustomerEmailAddress;
            this.OptionalPaymentParameter = OptionalPaymentParameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaymentUtilityOptionalParameterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaymentUtilityOptionalParameterResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string PaymentUtilityOptionalParameterResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RequestKey;
        
        public PaymentUtilityOptionalParameterResponse()
        {
        }
        
        public PaymentUtilityOptionalParameterResponse(string PaymentUtilityOptionalParameterResult, string RequestKey)
        {
            this.PaymentUtilityOptionalParameterResult = PaymentUtilityOptionalParameterResult;
            this.RequestKey = RequestKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BillPaymentUtility", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BillPaymentUtilityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string CardAcqID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public long OrderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string transactionKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string BillList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string TerminalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string RedirectURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string MerchantAdditionalData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string CustomerEmailAddress;
        
        public BillPaymentUtilityRequest()
        {
        }
        
        public BillPaymentUtilityRequest(string CardAcqID, long OrderId, string transactionKey, string BillList, string TerminalId, string RedirectURL, string MerchantAdditionalData, string CustomerEmailAddress)
        {
            this.CardAcqID = CardAcqID;
            this.OrderId = OrderId;
            this.transactionKey = transactionKey;
            this.BillList = BillList;
            this.TerminalId = TerminalId;
            this.RedirectURL = RedirectURL;
            this.MerchantAdditionalData = MerchantAdditionalData;
            this.CustomerEmailAddress = CustomerEmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BillPaymentUtilityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BillPaymentUtilityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string BillPaymentUtilityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RequestKey;
        
        public BillPaymentUtilityResponse()
        {
        }
        
        public BillPaymentUtilityResponse(string BillPaymentUtilityResult, string RequestKey)
        {
            this.BillPaymentUtilityResult = BillPaymentUtilityResult;
            this.RequestKey = RequestKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchTransferUtility", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BatchTransferUtilityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string CardAcqID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string transactionKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string CardList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string TerminalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string RedirectURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string MerchantAdditionalData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string CustomerEmailAddress;
        
        public BatchTransferUtilityRequest()
        {
        }
        
        public BatchTransferUtilityRequest(string CardAcqID, string transactionKey, string CardList, string TerminalId, string RedirectURL, string MerchantAdditionalData, string CustomerEmailAddress)
        {
            this.CardAcqID = CardAcqID;
            this.transactionKey = transactionKey;
            this.CardList = CardList;
            this.TerminalId = TerminalId;
            this.RedirectURL = RedirectURL;
            this.MerchantAdditionalData = MerchantAdditionalData;
            this.CustomerEmailAddress = CustomerEmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchTransferUtilityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BatchTransferUtilityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string BatchTransferUtilityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RequestKey;
        
        public BatchTransferUtilityResponse()
        {
        }
        
        public BatchTransferUtilityResponse(string BatchTransferUtilityResult, string RequestKey)
        {
            this.BatchTransferUtilityResult = BatchTransferUtilityResult;
            this.RequestKey = RequestKey;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface MerchantUtilitySoapChannel : Ir.Shaparak.Sadad.MerchantUtilitySoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MerchantUtilitySoapClient : System.ServiceModel.ClientBase<Ir.Shaparak.Sadad.MerchantUtilitySoap>, Ir.Shaparak.Sadad.MerchantUtilitySoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MerchantUtilitySoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MerchantUtilitySoapClient.GetBindingForEndpoint(endpointConfiguration), MerchantUtilitySoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MerchantUtilitySoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MerchantUtilitySoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MerchantUtilitySoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MerchantUtilitySoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MerchantUtilitySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckRequestStatusWithRealTransactionDateTimeResponse> CheckRequestStatusWithRealTransactionDateTimeAsync(Ir.Shaparak.Sadad.CheckRequestStatusWithRealTransactionDateTimeRequest request)
        {
            return base.Channel.CheckRequestStatusWithRealTransactionDateTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckRequestStatusResponse> CheckRequestStatusAsync(Ir.Shaparak.Sadad.CheckRequestStatusRequest request)
        {
            return base.Channel.CheckRequestStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckRequestStatusExResponse> CheckRequestStatusExAsync(Ir.Shaparak.Sadad.CheckRequestStatusExRequest request)
        {
            return base.Channel.CheckRequestStatusExAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckRequestStatusExWithRealTransactionDateTimeResponse> CheckRequestStatusExWithRealTransactionDateTimeAsync(Ir.Shaparak.Sadad.CheckRequestStatusExWithRealTransactionDateTimeRequest request)
        {
            return base.Channel.CheckRequestStatusExWithRealTransactionDateTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckStatusResult> CheckRequestStatusResultAsync(long OrderID, string CardAcqID, string TerminalID, string TransactionKey, string RequestKey, long AmountTrans)
        {
            return base.Channel.CheckRequestStatusResultAsync(OrderID, CardAcqID, TerminalID, TransactionKey, RequestKey, AmountTrans);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckStatusResult> GetRequestStatusResultAsync(long OrderID, string CardAcqID, string TerminalID, string TransactionKey, string RequestKey, long AmountTrans)
        {
            return base.Channel.GetRequestStatusResultAsync(OrderID, CardAcqID, TerminalID, TransactionKey, RequestKey, AmountTrans);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckStatusResult> GetAuthRequestStatusAsync(string CardAcqID, string TerminalID, long OrderID, string RequestKey, string CardNumber)
        {
            return base.Channel.GetAuthRequestStatusAsync(CardAcqID, TerminalID, OrderID, RequestKey, CardNumber);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckStatusResult> CheckBatchTransferStatusAsync(string CardAcqID, string TerminalID, long OrderID, string RequestKey, string CardNum, long Amount)
        {
            return base.Channel.CheckBatchTransferStatusAsync(CardAcqID, TerminalID, OrderID, RequestKey, CardNum, Amount);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.CheckStatusResult> CheckBillStatusAsync(string CardAcqID, string TerminalID, long OrderID, string RequestKey, long BillID, long BillPaymentID)
        {
            return base.Channel.CheckBillStatusAsync(CardAcqID, TerminalID, OrderID, RequestKey, BillID, BillPaymentID);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.GetSpecificMerchantCommitReportByPageNumberResponse> GetSpecificMerchantCommitReportByPageNumberAsync(Ir.Shaparak.Sadad.GetSpecificMerchantCommitReportByPageNumberRequest request)
        {
            return base.Channel.GetSpecificMerchantCommitReportByPageNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.GetCommitReportByPageNumberResponse> GetCommitReportByPageNumberAsync(Ir.Shaparak.Sadad.GetCommitReportByPageNumberRequest request)
        {
            return base.Channel.GetCommitReportByPageNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.GetCommitReportResponse> GetCommitReportAsync(Ir.Shaparak.Sadad.GetCommitReportRequest request)
        {
            return base.Channel.GetCommitReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.GetTransactionReportResponse> GetTransactionReportAsync(Ir.Shaparak.Sadad.GetTransactionReportRequest request)
        {
            return base.Channel.GetTransactionReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.GetTransactionReportByPageNumberResponse> GetTransactionReportByPageNumberAsync(Ir.Shaparak.Sadad.GetTransactionReportByPageNumberRequest request)
        {
            return base.Channel.GetTransactionReportByPageNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.GetTransactionReportWithSettlementDateByPageNumberResponse> GetTransactionReportWithSettlementDateByPageNumberAsync(Ir.Shaparak.Sadad.GetTransactionReportWithSettlementDateByPageNumberRequest request)
        {
            return base.Channel.GetTransactionReportWithSettlementDateByPageNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> GeneratePaymentIDAsync(string ID)
        {
            return base.Channel.GeneratePaymentIDAsync(ID);
        }
        
        public System.Threading.Tasks.Task<bool> ValidatePaymentIDAsync(string ID)
        {
            return base.Channel.ValidatePaymentIDAsync(ID);
        }
        
        public System.Threading.Tasks.Task<string> GenerateCheckDigitAsync(string ID)
        {
            return base.Channel.GenerateCheckDigitAsync(ID);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.PaymentUtilityResponse> PaymentUtilityAsync(Ir.Shaparak.Sadad.PaymentUtilityRequest request)
        {
            return base.Channel.PaymentUtilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.PaymentUtilityAdditionalDataResponse> PaymentUtilityAdditionalDataAsync(Ir.Shaparak.Sadad.PaymentUtilityAdditionalDataRequest request)
        {
            return base.Channel.PaymentUtilityAdditionalDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.PaymentUtilityOptionalParameterResponse> PaymentUtilityOptionalParameterAsync(Ir.Shaparak.Sadad.PaymentUtilityOptionalParameterRequest request)
        {
            return base.Channel.PaymentUtilityOptionalParameterAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.BillPaymentUtilityResponse> BillPaymentUtilityAsync(Ir.Shaparak.Sadad.BillPaymentUtilityRequest request)
        {
            return base.Channel.BillPaymentUtilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ir.Shaparak.Sadad.BatchTransferUtilityResponse> BatchTransferUtilityAsync(Ir.Shaparak.Sadad.BatchTransferUtilityRequest request)
        {
            return base.Channel.BatchTransferUtilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> CalcTimeStampAsync()
        {
            return base.Channel.CalcTimeStampAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MerchantUtilitySoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MerchantUtilitySoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MerchantUtilitySoap))
            {
                return new System.ServiceModel.EndpointAddress("https://sadad.shaparak.ir/MerchantUtility.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MerchantUtilitySoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://sadad.shaparak.ir/MerchantUtility.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MerchantUtilitySoap,
            
            MerchantUtilitySoap12,
        }
    }
}
